package engine.entities.components;

public enum ComponentType {
    HEALTH_COMPONENT, ATTACK_COMPONENT, WEAPON_COMPONENT, GRAPHICS_COMPONENT, TRANSFORM_COMPONENT,
    COLLISION_COMPONENT, INPUT_COMPONENT, AUDIO_COMPONENT
}
