package engine.entities.composites;

public enum ComponentType {
    HEALTH_COMPONENT, ATTACK_COMPONENT, WEAPON_COMPONENT, GRAPHICS_COMPONENT, TRANSFORM_COMPONENT,
    COLLISION_COMPONENT, INPUT_COMPONENT
}
